# GitHub Pages configuration for Hugo + Quarto Documentation System
# This serves the installation page and install script

title: "Hugo + Quarto Documentation System"
description: "A modern documentation platform with Hugo and Quarto"
url: "https://accionlabs.github.io"
baseurl: "/hugo-quarto-docs"

# GitHub Pages settings
plugins:
  - jekyll-github-metadata

# Include shell scripts
include:
  - install.sh

# Exclude other files
exclude:
  - README.md